// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: proto/msg/login.proto

package msg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 登录认证
type C2S_10001 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *C2S_10001) Reset() {
	*x = C2S_10001{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_10001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_10001) ProtoMessage() {}

func (x *C2S_10001) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_10001.ProtoReflect.Descriptor instead.
func (*C2S_10001) Descriptor() ([]byte, []int) {
	return file_proto_msg_login_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_10001) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type S2C_10001 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2C_10001) Reset() {
	*x = S2C_10001{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_10001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_10001) ProtoMessage() {}

func (x *S2C_10001) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_10001.ProtoReflect.Descriptor instead.
func (*S2C_10001) Descriptor() ([]byte, []int) {
	return file_proto_msg_login_proto_rawDescGZIP(), []int{1}
}

// 选择角色
type C2S_10002 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2S_10002) Reset() {
	*x = C2S_10002{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_10002) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_10002) ProtoMessage() {}

func (x *C2S_10002) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_10002.ProtoReflect.Descriptor instead.
func (*C2S_10002) Descriptor() ([]byte, []int) {
	return file_proto_msg_login_proto_rawDescGZIP(), []int{2}
}

type S2C_10002 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2C_10002) Reset() {
	*x = S2C_10002{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_10002) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_10002) ProtoMessage() {}

func (x *S2C_10002) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_10002.ProtoReflect.Descriptor instead.
func (*S2C_10002) Descriptor() ([]byte, []int) {
	return file_proto_msg_login_proto_rawDescGZIP(), []int{3}
}

// 创建角色
type C2S_10003 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2S_10003) Reset() {
	*x = C2S_10003{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_login_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_10003) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_10003) ProtoMessage() {}

func (x *C2S_10003) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_login_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_10003.ProtoReflect.Descriptor instead.
func (*C2S_10003) Descriptor() ([]byte, []int) {
	return file_proto_msg_login_proto_rawDescGZIP(), []int{4}
}

type S2C_10003 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2C_10003) Reset() {
	*x = S2C_10003{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_login_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_10003) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_10003) ProtoMessage() {}

func (x *S2C_10003) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_login_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_10003.ProtoReflect.Descriptor instead.
func (*S2C_10003) Descriptor() ([]byte, []int) {
	return file_proto_msg_login_proto_rawDescGZIP(), []int{5}
}

// 无响应数据
type C2S_10004 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2S_10004) Reset() {
	*x = C2S_10004{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_login_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_10004) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_10004) ProtoMessage() {}

func (x *C2S_10004) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_login_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_10004.ProtoReflect.Descriptor instead.
func (*C2S_10004) Descriptor() ([]byte, []int) {
	return file_proto_msg_login_proto_rawDescGZIP(), []int{6}
}

var File_proto_msg_login_proto protoreflect.FileDescriptor

var file_proto_msg_login_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x21, 0x0a, 0x09,
	0x43, 0x32, 0x53, 0x5f, 0x31, 0x30, 0x30, 0x30, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x0b, 0x0a, 0x09, 0x53, 0x32, 0x43, 0x5f, 0x31, 0x30, 0x30, 0x30, 0x31, 0x22, 0x0b, 0x0a, 0x09,
	0x43, 0x32, 0x53, 0x5f, 0x31, 0x30, 0x30, 0x30, 0x32, 0x22, 0x0b, 0x0a, 0x09, 0x53, 0x32, 0x43,
	0x5f, 0x31, 0x30, 0x30, 0x30, 0x32, 0x22, 0x0b, 0x0a, 0x09, 0x43, 0x32, 0x53, 0x5f, 0x31, 0x30,
	0x30, 0x30, 0x33, 0x22, 0x0b, 0x0a, 0x09, 0x53, 0x32, 0x43, 0x5f, 0x31, 0x30, 0x30, 0x30, 0x33,
	0x22, 0x0b, 0x0a, 0x09, 0x43, 0x32, 0x53, 0x5f, 0x31, 0x30, 0x30, 0x30, 0x34, 0x42, 0x31, 0x5a,
	0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x62, 0x77, 0x66,
	0x72, 0x65, 0x65, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_msg_login_proto_rawDescOnce sync.Once
	file_proto_msg_login_proto_rawDescData = file_proto_msg_login_proto_rawDesc
)

func file_proto_msg_login_proto_rawDescGZIP() []byte {
	file_proto_msg_login_proto_rawDescOnce.Do(func() {
		file_proto_msg_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_msg_login_proto_rawDescData)
	})
	return file_proto_msg_login_proto_rawDescData
}

var file_proto_msg_login_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_msg_login_proto_goTypes = []interface{}{
	(*C2S_10001)(nil), // 0: msg.C2S_10001
	(*S2C_10001)(nil), // 1: msg.S2C_10001
	(*C2S_10002)(nil), // 2: msg.C2S_10002
	(*S2C_10002)(nil), // 3: msg.S2C_10002
	(*C2S_10003)(nil), // 4: msg.C2S_10003
	(*S2C_10003)(nil), // 5: msg.S2C_10003
	(*C2S_10004)(nil), // 6: msg.C2S_10004
}
var file_proto_msg_login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_msg_login_proto_init() }
func file_proto_msg_login_proto_init() {
	if File_proto_msg_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_msg_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_10001); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_10001); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_10002); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_10002); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_login_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_10003); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_login_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_10003); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_login_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_10004); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_msg_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_msg_login_proto_goTypes,
		DependencyIndexes: file_proto_msg_login_proto_depIdxs,
		MessageInfos:      file_proto_msg_login_proto_msgTypes,
	}.Build()
	File_proto_msg_login_proto = out.File
	file_proto_msg_login_proto_rawDesc = nil
	file_proto_msg_login_proto_goTypes = nil
	file_proto_msg_login_proto_depIdxs = nil
}
